Working lock and unlock

diff --git a/lock b/lock
--- a/lock
+++ b/lock
@@ -2,7 +2,7 @@
 
 javac lock.java
 javac rsa_sign.java
-while getopts :d:p:r:v: option
+while getopts :d:p:r: option
 	do
 		case "$option" in
 		d)
@@ -13,14 +13,11 @@ while getopts :d:p:r:v: option
 			;;
 		r)	privkey="$OPTARG"
 			;;
-		v)	vpk="$OPTARG"
-			;;
 			esac
 	done
-
 #Lock creates an AES key, encrypts it with pubkey, and writes to symmetric key manifest
 ca=$pubkey'-casig'
-./rsa-validate \-k $vpk -m $pubkey -s $ca | grep 'False' && echo "Invalid public key" && exit 1
+./rsa-validate \-k $8 -m $pubkey -s $ca | grep 'False' && echo "Invalid public key" && exit 1
 echo "Public Key validated by Signing Authority"
 java lock $directory $pubkey
 java rsa_sign \-k $privkey -m $directory'/manifest' \-s $directory'/manifest.sig'
diff --git a/unlock b/unlock
--- a/unlock
+++ b/unlock
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 javac unlock.java
-while getopts :d:p:r:v: option
+while getopts :d:p:r: option
 	do
 		case "$option" in
 		d)
@@ -12,13 +12,11 @@ while getopts :d:p:r:v: option
 			;;
 		r)	privkey="$OPTARG"
 			;;
-		v)	vpk="$OPTARG"
-			;;
 			esac
 	done
 
 ca=$pubkey'-casig'
-./rsa-validate \-k $vpk \-m $pubkey \-s $ca | grep 'False' && echo "Invalid public key" && exit 1
+./rsa-validate \-k $8 \-m $pubkey \-s $ca | grep 'False' && echo "Invalid public key" && exit 1
 echo "Public Key validated by Signing Authority"
 ./rsa-validate \-k $pubkey -m $directory'/manifest' \-s $directory'/manifest.sig' | grep 'False' && echo "Manifest Signature error" && exit 1
 echo "Symmetric Key Manifest Integrity Verified"
